### POST request to example server
POST http://127.0.0.1:8080/create-developer
Content-Type: application/json

{
    "developerSkillType": "FRONT_END",
    "developerLevel": "JUNIOR",
    "name": "ASD",
    "age": 25,
    "experienceYears": 2,
    "memberId": "asd"
}